#!/usr/bin/env python3
"""Embed the initial page fonts in the shared render-blocking stylesheet."""

import base64
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
START = "/* Generated by scripts/embed-page-fonts.py; do not edit this block. */"
END = "/* End embedded page fonts. */"
FONTS = (
    ("Inter", "inter-page.woff2", "normal"),
    ("Inter", "inter-page-italic.woff2", "italic"),
    ("Geist Mono", "geist-mono-variable.woff2", "normal"),
)


def main() -> None:
    stylesheet = ROOT / "styles.css"
    current = stylesheet.read_text(encoding="utf-8")
    if current.count(START) != 1 or current.count(END) != 1:
        raise SystemExit("styles.css must contain exactly one embedded-font block")
    before, block = current.split(START, 1)
    _, after = block.split(END, 1)
    faces = []
    for family, filename, style in FONTS:
        encoded = base64.b64encode((ROOT / "static" / filename).read_bytes()).decode("ascii")
        faces.append(
            "@font-face {\n"
            f'  font-family: "{family}";\n'
            f'  src: url("data:font/woff2;base64,{encoded}") format("woff2");\n'
            f"  font-style: {style};\n"
            "  font-weight: 100 900;\n"
            "  font-display: block;\n"
            "}"
        )
    updated = before + START + "\n" + "\n\n".join(faces) + "\n" + END + after
    if updated != current:
        stylesheet.write_text(updated, encoding="utf-8")
        print("Updated embedded Inter and Geist Mono in styles.css")


if __name__ == "__main__":
    main()
