#!/usr/bin/env python3
"""Vendor the pinned Swup browser bundles and their MIT license notices."""

import base64
import hashlib
import io
import json
from pathlib import Path
import re
import tarfile
from urllib.request import urlopen

ROOT = Path(__file__).resolve().parents[1]
PACKAGES = [
    ("swup", "4.10.0", "dist/Swup.umd.js",
     "sha512-bzl5u94ovy5YDc+6No28De2TgMWK47Ym0uuMpN9kmzu+NWm3/mhQrmRPjArsFpfVTWO1nMFUZrKRwpRjS6eNJg=="),
    ("@swup/head-plugin", "2.3.1", "dist/index.umd.js",
     "sha512-kdv60fO9c0/3+K40f7Fj/uV34nSuuPeCsld83J5uVVFizOmoovA737C5M1Iqac5Spf2GLU7q+mhN6AbohSIBjA=="),
    ("@swup/a11y-plugin", "5.2.1", "dist/index.umd.js",
     "sha512-n7gphzG+LBuE1RZVYpMxVELqDVFtUNhbehoVZsUiKXaAEkQV64YASe42XmffRnwzmLVtNHBFOSUKd21whctUBg=="),
    ("delegate-it", "6.0.0", None,
     "sha512-aJNQUTyDcj4qSkbXH2d7QzKEX5Lgg4s0yprxaC2GIBKAN/jj3S0657cGN9x0JlzEn0lEY7hwg0Z1ITdjkrfXbA=="),
    ("@swup/plugin", "4.0.0", None,
     "sha512-3Kq31BJxnzoPg643YxGoWQggoU6VPKZpdE5CqqmP7wwkpCYTzkRmrfcQ29mGhsSS7xfS7D33iZoBiwY+wPoo2A=="),
    ("focus-options-polyfill", "1.5.0", None,
     "sha512-HiMSaXGUz2OFjOuoGTWXlp+YjZCGnVXPu6vPeccgaSOzGmqLVz8tJRcKXWfMJnj16LXf/IM1rJI0zrZMVc9q7g=="),
]


def main():
    bundles = ["/* Generated by scripts/vendor-navigation.py. See navigation-vendor.LICENSE.txt. */"]
    notices = []
    for name, version, bundle, integrity in PACKAGES:
        with urlopen(f"https://registry.npmjs.org/{name}/{version}", timeout=30) as response:
            package = json.load(response)
        with urlopen(package["dist"]["tarball"], timeout=30) as response:
            archive = response.read()
        algorithm, expected = integrity.split("-", 1)
        actual = base64.b64encode(hashlib.new(algorithm, archive).digest()).decode()
        if actual != expected:
            raise ValueError(f"Integrity mismatch for {name}@{version}")
        with tarfile.open(fileobj=io.BytesIO(archive), mode="r:gz") as tar:
            licenses = [member for member in tar.getnames()
                        if member.lower() in ("package/license", "package/license.txt", "package/license.md")]
            if len(licenses) != 1:
                raise ValueError(f"Expected one license in {name}@{version}: {licenses}")
            notice = tar.extractfile(licenses[0]).read().decode()
            notices.append(f"{name}@{version}\n{package['dist']['tarball']}\n\n{notice}")
            if bundle:
                source = tar.extractfile(f"package/{bundle}").read().decode()
                source = re.sub(r"(?m)^//# sourceMappingURL=.*$", "", source).rstrip()
                bundles.append(f"/* {name}@{version} */\n{source}\n;")
    (ROOT / "static/navigation-vendor.js").write_text("\n".join(bundles) + "\n")
    (ROOT / "static/navigation-vendor.LICENSE.txt").write_text("\n\n".join(notices))
    print("Vendored pinned navigation bundles and license notices")


if __name__ == "__main__":
    main()
